"""Initial tables

Revision ID: 01864dbd1ad6
Revises: 
Create Date: 2024-10-17 11:21:09.576248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01864dbd1ad6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pk', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('potion',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pk', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('potion_ingredient',
    sa.Column('potion_id', sa.UUID(), nullable=True),
    sa.Column('ingredient_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.pk'], ),
    sa.ForeignKeyConstraint(['potion_id'], ['potion.pk'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('potion_ingredient')
    op.drop_table('potion')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
